apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend

spec:
  template:
    metadata:
      name: pod-my-nginx
      labels:
        env: production
    spec:
      containers:
        - name: nginx-container
          image: nginx
  
  selector:
    matchLabels:
      env: production
  strategy:
    type: Recreate #RollingUpdate
  replicas: 4
